import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MetaPixel from "@/components/MetaPixel";
import Script from "next/script"; // Import Script for nonce

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = crypto.randomBytes(16).toString('base64'); // Generate nonce for CSP

  return (
    <html lang="en">
      <head>
        {/* Google Tag Manager */}
        <script
          nonce={nonce} // Apply nonce to GTM script
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WM5S3M6X');`,
          }}
        />
        {/* End Google Tag Manager */}
        <link
          href="https://fonts.googleapis.com/css2?family=Road+Rage&family=Roboto+Condensed:wght@400;700&family=Oswald:wght@400;700&display=swap"
          rel="stylesheet"
        />
        {/* Content Security Policy - REMOVED, rely on nonce via GTM */}
        {/* <meta
          http-equiv="Content-Security-Policy"
          content="..." 
        /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-WM5S3M6X"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        {/* End Google Tag Manager (noscript) */}
        <MetaPixel />
        {children}
      </body>
    </html>
  );
}
